services:
  db:
    image: postgres:17
    container_name: movie_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/createDatabase_V2.sql:/docker-entrypoint-initdb.d/createDatabase_V2.sql

  backend:
    build: ./backend
    container_name: movie_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
    depends_on:
      - db


  frontend:
    restart: unless-stopped
    build: 
      context: ./frontend
      args:
        VITE_API_URL: /api
    container_name: movie_frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend

volumes:
  postgres_data: