-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."user"
(
    userid integer NOT NULL,
    username character varying(32) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    "registrationDate" date DEFAULT CURRENT_DATE,
    CONSTRAINT "USERID PRIMARYKEY" PRIMARY KEY (userid),
    CONSTRAINT "UniqueUsernamesOnly" UNIQUE (username),
    CONSTRAINT "UniqueEmailsOnly" UNIQUE (email)
);

COMMENT ON COLUMN public."user".username
    IS '32 username length constraint, also add unique somewhere somehow';

CREATE TABLE IF NOT EXISTS public."group"
(
    groupid integer,
    ownerid integer,
    groupname character varying(32) NOT NULL,
    groupdescription character varying(255),
    PRIMARY KEY (groupid),
    CONSTRAINT "UniqueGroupNamesOnly" UNIQUE (groupname)
);

CREATE TABLE IF NOT EXISTS public."user-group-linker"
(
    groupid integer,
    userid integer
);

CREATE TABLE IF NOT EXISTS public.review
(
    reviewid integer,
    movieid integer NOT NULL,
    stars integer NOT NULL,
    useremail character varying(32) NOT NULL,
    reviewtext character varying(1000),
    reviewdate date NOT NULL DEFAULT CURRENT_DATE,
    PRIMARY KEY (reviewid)
);

CREATE TABLE IF NOT EXISTS public.groupposts
(
    postid bigint,
    groupid bigint NOT NULL,
    posttext character varying(1000),
    movieid bigint,
    postdate date DEFAULT CURRENT_DATE,
    PRIMARY KEY (groupid),
    CONSTRAINT uniquepk UNIQUE (postid)
);

CREATE TABLE IF NOT EXISTS public.favoritemovies
(
    favmovieid integer NOT NULL,
    userid integer NOT NULL,
    movieid integer NOT NULL,
    PRIMARY KEY (favmovieid),
    CONSTRAINT uniquepk UNIQUE (favmovieid)
);

ALTER TABLE IF EXISTS public."user-group-linker"
    ADD CONSTRAINT userid FOREIGN KEY (userid)
    REFERENCES public."user" (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."user-group-linker"
    ADD CONSTRAINT groupid FOREIGN KEY (groupid)
    REFERENCES public."group" (groupid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.review
    ADD CONSTRAINT "userEmailInReview" FOREIGN KEY (useremail)
    REFERENCES public."user" (email) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.groupposts
    ADD CONSTRAINT groupid FOREIGN KEY (groupid)
    REFERENCES public."group" (groupid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.favoritemovies
    ADD CONSTRAINT userid FOREIGN KEY (userid)
    REFERENCES public."user" (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;