### GROUP POSTS CRUD OPERATIONS ###
@token=putyourtokenhere
### Get All Group Posts
GET http://localhost:3000/groupposts/

### Get Group Posts by Group ID
GET http://localhost:3000/groupposts/groupid/1

### Get Group Posts by Post ID
GET http://localhost:3000/groupposts/postid/1

### Create Group Post
POST http://localhost:3000/groupposts/post
Content-Type: application/json
Authorization: {{token}}

{
    "groupposts": {
        "groupid": 1,
        "posttext": "Suosittelen tätä leffaa kaikille",
        "movieid": 157336
    }
}

### Update Group Post
PUT http://localhost:3000/groupposts/update/4
Content-Type: application/json
Authorization: {{token}}

{
    "groupposts": {
        "posttext": "Päivitetty teksti",
        "movieid": 157336
    }
}

### Delete Group Post
DELETE http://localhost:3000/groupposts/delete/2
Authorization: {{token}}